### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by thorwebdev** [tawn33y/whatsapp-cloud-api#18]
Nice work. I was wondering, any plans to add Deno support? Similar to grammY maybe? Can see an example here: https://github.com/grammyjs/examples/blob/main/supabase-edge-functions/supabase/functions/telegram-bot/index.ts

**Comment by tawn33y** [comment]
Hi @thorwebdev,

This looks exciting. It isn't on the roadmap but I will try to give it a go. No ETA for now though.

Feel free to give it a whirl too :)

**Comment by tawn33y** [comment]
Marking this as closed for now since it is not on the roadmap. Feel free to give it a go in the meantime.
