### ISSUE TITLE
I can't send a list

### ISSUE THREAD

**Issue by jkupovic** [tawn33y/whatsapp-cloud-api#20]
I do not know how to do it

```
let sections = [{
            "title": "Afternoon slots",
            "rows": [{"id": "1",
                    "title": "13:00",
                    "description": "Collection: Crouch End Bakery"
                },
                {"id": "2",
                    "title": "13:30",
                    "description": "Collection: Hampstead Bakery"
                },
                {"id": "3",
                    "title": "13:00",
                    "description": "Collection: Hampstead Bakery"
                }
            ]
        },
        {
            "title": "Evening slots",
            "rows": [{"id": "4",
                    "title": "18:00",
                    "description": "Collection: Crouch End Bakery"
                },
                {"id": "5",
                    "title": "18:30",
                    "description": "Collection: Hampstead Bakery"
                },
                {"id": "6",
                    "title": "17:00",
                    "description": "Collection: Crouch End Bakery"
                }
            ]
        }
    ];
const result4 = await bot.sendList(to, 'asdf', 'fdsa', sections, '');
```

what is the mistake?

**Comment by RyzorBent** [comment]
hi @jkupovic 

the below code worked for me.

         `await bot.sendList(to, 'JustList', 'this is the body text', {
                'test section tile': [
                  {
                    id: 'sec_id',
                    title: 'sec title',
                    description: 'sec description',
                  },
                  {
                    id: 'sec_id2',
                    title: 'sec title2',
                    description: 'sec description2',
                  },
                  {
                    id: 'sec_id3',
                    title: 'sec title3',
                    description: 'sec description3',
                  },
                  {
                    id: 'sec_id4',
                    title: 'sec title4',
                    description: 'sec description4',
                  },
                ],
              });`

<img width="1022" alt="Screenshot 2022-08-07 at 17 26 55" src="https://user-images.githubusercontent.com/15725743/183298483-3d32f839-22b1-47a8-9b71-9e29bff9f21d.png">

**Comment by jkupovic** [comment]
Thank you very much, it works perfectly
=D
