### ISSUE TITLE
Where to get name of the sender

### ISSUE THREAD

**Issue by RyzorBent** [tawn33y/whatsapp-cloud-api#21]
https://github.com/tawn33y/whatsapp-cloud-api/blob/dd73985e97539dd70f4eb74ee256eef63dda2062/src/startExpressServer.ts#L71

Where on the api can i get the **name** of the sender, When i check the **from key** it only has cellNumber of the sender but no name

bot.on('message', async (msg) => {
      console.log(msg.from.name);  //undefined 
      console.log(msg.from); //+27xxxxxxxxxx
}

**Comment by guskuma** [comment]
Hello there. I don't think this information is available in msg payload, as per https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/components

**Comment by RyzorBent** [comment]
Hi @guskuma, 

i managed to get the name working on my local machine, can i make a pull request on this issue, o have to open a new issue for this feature?

**Comment by guskuma** [comment]
Hello @RyzorBent I'd say you can make a pull request. I do not own this repo but I guess any help is appreciated, right @tawn33y ?

**Comment by tawn33y** [comment]
@RyzorBent @guskuma Sure thing! I've reopened the issue. Feel free to open a PR on the same. Here's a guideline on the process: https://gist.github.com/tawn33y/a380c176265d5b060c5c722f1e89d79f

**Comment by RyzorBent** [comment]
@tawn33y i'm struggling with jest testing, in order to commit changes

perhaps you could do the change on you end? This is the code sniped to get the whatsApp user name

 `const name = req.body.entry[0].changes[0].value.contacts?.length
      ? req.body.entry[0].changes[0].value.contacts[0].profile.name
      : null;`

**Comment by guskuma** [comment]
Where do you guys think this property should be? New Message property "fromName"? Or maybe set from into object with wa_id and name properties?

**Comment by tawn33y** [comment]
@guskuma ,I think it's best to set it under `msg.from.name` since the `from` property contains other details of the sender. 

@RyzorBent, I can help you with the jest testing. Feel free to share where you are stuck. If unable, happy to take it up for you.

**Comment by RyzorBent** [comment]
@tawn33y, when i run `npm t` i get this 14 passes and 2 fails : which has to do with the verifying the token.


<img width="1440" alt="Screenshot 2022-08-12 at 08 01 02" src="https://user-images.githubusercontent.com/15725743/184294049-55099c71-3c46-4219-ab98-04ecb083cea3.png">

**Comment by RyzorBent** [comment]
@tawn33y @guskuma Greetings,

Is there an _impediment_ which is preventing this pull request to go through?

**Comment by tawn33y** [comment]
Hi @RyzorBent, I'm waiting for @guskuma to address some comments I left on the PR 😊

**Comment by guskuma** [comment]
Hey there! @tawn33y I've made changes to PR, it's ready to be reviewed. Thank you.

**Comment by tawn33y** [comment]
@guskuma I've added some comments on the comments you might have missed. Kindly have a look

**Comment by tawn33y** [comment]
Fixed by #25
