### ISSUE TITLE
Message context is not captured when message type is not of "interactive" type

### ISSUE THREAD

**Issue by guskuma** [tawn33y/whatsapp-cloud-api#22]
When a message is a reply or is forwarded context field is filled but not captured by this API.

**Comment by guskuma** [comment]
I'll work add it "data" field whenever it's content is not null (just like when message is 'interactive' type).

**Comment by guskuma** [comment]
@tawn33y I wasn't able to push changes to repo. I think permission is needed. Could you take a look into?

`git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feature/ISSUE-22:refs/heads/feature/ISSUE-22 --set-upstream
remote: Permission to tawn33y/whatsapp-cloud-api.git denied to guskuma.
fatal: unable to access 'https://github.com/tawn33y/whatsapp-cloud-api.git/': The requested URL returned error: 403`

**Comment by tawn33y** [comment]
I've added you as a Collaborator. Try again?

**Comment by tawn33y** [comment]
I've added you as a Collaborator. Try again?

**Comment by guskuma** [comment]
Still no luck, same error!
