### ISSUE TITLE
how to pass variables 

### ISSUE THREAD

**Issue by AlfaDigitals** [tawn33y/whatsapp-cloud-api#26]
for(let i=0;i<2;i++){
    const result = await bot.sendTemplate(to[i], 'charge_alert', 'en_US', [
      {
        "type": "body",
        "parameters": [{
                     "type": "text",
                     "text": {me}
                     },
                     {
                      "type": "text",
                      "text": {friend}
                      },
                      {
                        "type": "text",
                        "text": {msg}
                        
                        }
                 ]
       }
    ])
   }
  
  } catch (err) {
    console.log(err);
  }

#All works fine except when variable are passed it does't work

**Comment by tawn33y** [comment]
From [the official documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#template-object):

```js
const to = 'PHONE_NUMBER_OF_RECIPIENT';

// text
const result = await bot.sendTemplate(to, 'charge_alert', 'en_US', [
  {
    type: 'body',
    parameters: [
      {
        type: 'text',
        text: 'Hi there'
      },
    ]
  }
]);

// button
const result = await bot.sendTemplate(to, 'charge_alert', 'en_US', [
  {
    type: 'button',
    sub_type: 'url',
    index: 0,
    parameters: [
      {
        type: 'text',
        text: 'name'
      },
    ],
  },
]);

// currency
const result = await bot.sendTemplate(to, 'charge_alert', 'en_US', [
  {
    type: 'body',
    parameters: [
      {
        type: 'currency',
        currency: {
          fallback_value: '$10',
          code: 'USD',
          amount_1000: 10
        }
      },
    ]
  }
]);

// datetime
const result = await bot.sendTemplate(to, 'charge_alert', 'en_US', [
  {
    type: 'body',
    parameters: [
      {
        type: 'date_time',
        fallback_value: '15th Aug 2022'
      }
    ]
  }
]);
```

If you're using variables and it's failing, this can be due to the data types, i.e. it's expecting a string type but you're using a number. The easiest way is to log the error message to find the root cause:

```js
try {
  const result = await bot.sendTemplate(to, 'charge_alert', 'en_US', [
    {
      type: 'body',
      parameters: [
        {
          type: 'text',
          text: {me}
        },
      ]
    }
  ]);
} catch (err) {
  console.log(err);
} 
```

Try this & let me know if it works.
