### ISSUE TITLE
Read express port from environment 

### ISSUE THREAD

**Issue by tawn33y** [tawn33y/whatsapp-cloud-api#36]
From #19

Add functionality to read the server port from `process.env`

Suggested change from #19:

```js
// startExpressServer.js line 100

// change
const port = options?.port || 3000;

// to
const port = options?.port || process.env.PORT || 3000;
```

**Comment by TEMHITHORPHE** [comment]
This looks trivial to support, can I do this??

**Comment by tawn33y** [comment]
Definitely! 😊

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
