### ISSUE TITLE
receive image and save it

### ISSUE THREAD

**Issue by jkupovic** [tawn33y/whatsapp-cloud-api#37]
Hello everyone, is it possible to save an image that the user sends?

  data: {
    mime_type: 'image/jpeg',
    sha256: '7P5nRXlN6yADTMqgDrqzycfaNWsddEQHOtHGN6hZxM4=',
    id: '5512756692174447'
  }

I don't understand how to do it
thanks

**Comment by jkupovic** [comment]
I found it

latercurl \
  'https://graph.facebook.com/v15.0/MEDIA_ID' \
  -H 'Authorization: Bearer ACCESS_TOKEN'


later


curl  \
 'URL' \
 -H 'Authorization: Bearer ACCESS_TOKEN' > media_file


now i will make a function

**Comment by tawn33y** [comment]
Glad you solved it!

**Comment by HannoVorster** [comment]
@jkupovic, did you managed to get it working?

I have tried to test it, but it seems that Meta is still working on their functionality.

After running the CURL, I receive a URL back as a response =>
![image](https://user-images.githubusercontent.com/17809351/197708771-90b68d26-ad58-4ac9-af2a-7719c968abbb.png)

When you open the URL to view the image, then I see a screen with message "Sorry, something went wrong." =>
![image](https://user-images.githubusercontent.com/17809351/197708864-378cea9d-cbd8-4212-912f-e1e40bae758a.png)

Any luck from your side?

**Comment by TEMHITHORPHE** [comment]
What does a solution look like? ... I'm assuming it doesn't involve calling `curl` ...

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
