### ISSUE TITLE
Send "Read" status

### ISSUE THREAD

**Issue by alfonsusac** [tawn33y/whatsapp-cloud-api#38]
Allows developer to send "Read" status
Preferably using the existing method `bot.sendMessage()` or a new one like `bot.sendStatus()`

Official documentation: 
https://developers.facebook.com/docs/whatsapp/cloud-api/guides/mark-message-as-read

**Comment by tawn33y** [comment]
Well noted, @alfonsusac.

Will pick this up.

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
