### ISSUE TITLE
help with list_reply

### ISSUE THREAD

**Issue by kev095** [tawn33y/whatsapp-cloud-api#39]
Hello, I have a question when I send a list of options (list_reply) and the user enters an "account status" option and then enters the document number. How do I get that value going through the previous validations again?

![image](https://user-images.githubusercontent.com/115809256/197563344-c217d755-3f80-4043-86a4-20ead7a9e7c5.png)

**Comment by tawn33y** [comment]
You need a cache or database to persist this. Let's say you have a series of inputs, eg first name, last name, document number, etc, you need to save each of these during the step when the user replies. 

This can also prove useful especially if the server restarts in the middle of a conversation as the user won't have to start answering the questions from the top.

Here's an example:

```js
let cache = {}; // can be redis, sql, etc 

if (msg.type === 'list_reply') {
  if (msg.data.id === 'first_name') {
    cache = { ...cache, firstName: msg.data.text };
    // send reply, proceed to next step, etc
  } else if (msg.data.id === 'document_number') {
    cache = { ...cache, documentNumber: msg.data.text };
    // send reply, proceed to next step, etc
  } else if (msg.data.id === 'email') {
    cache = { ...cache, email: msg.data.text };
    // send reply, proceed to next step, etc
  }
} 
```

**Comment by kev095** [comment]
Thank you very much for your answer, your successful project is great!

**Comment by tawn33y** [comment]
You're most welcome. Thank you very much! 😊

**Comment by tawn33y** [comment]
Marking this as closed for now. @kev095, feel free to reopen if need be 😊
