### ISSUE TITLE
Pull Request for adding the ability to read Status payload

### ISSUE THREAD

**Issue by alfonsusac** [tawn33y/whatsapp-cloud-api#44]

**Comment by RyzorBent** [comment]
Hi @tawn33y any update on this issue, is there a reason why it is not merged?

**Comment by tawn33y** [comment]
@RyzorBent  I think there were several unresolved comments on the PR.

![image](https://github.com/tawn33y/whatsapp-cloud-api/assets/21337194/244510de-151c-49ac-ba98-c595d792159d)

I think I will go ahead and work on them myself so that we can close it

**Comment by RyzorBent** [comment]
@tawn33y, if there's anything i can do to assist with the work-load do let me know.

**Comment by RyzorBent** [comment]
Hi @tawn33y is there any task I can assist with on this issue? 🙂 As I hopping to include this feature in my SaaS app.

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
