### ISSUE TITLE
sendSticker fails to send without throwing error

### ISSUE THREAD

**Issue by mrkencable** [tawn33y/whatsapp-cloud-api#45]
i am able to successfully 
SendText and SendVideo, however  bot.sendSticker, using the url of a webp file fails:

try{
				  await bot.sendSticker(from, msgUrl);
				  console.log(`sticker sent`);
				  res.status(200).send('Sticker Sent');
				  }catch(err){
					  console.log(`get/sendsticker error:`,err);
					res.status(200).send({message:'Error sending Sticker',"to":from,"text":msgText});
				  }

Results:
no error is thrown, 
"sticker sent" displayed,
but the sticker is not sent to my whatsapp ....    
using url:  https://pelicansecured.com/mobilemenu/assets/imgs/delivery_on_the_way.webp

**Comment by tawn33y** [comment]
Sorry for the late reply. If you [look closely at my tests](https://github.com/tawn33y/whatsapp-cloud-api/blob/main/src/createBot.test.ts#L89), I never seemed to get `sendSticker` working. It always failed to deliver the sticker.

I couldn't figure out the file extension needed or the right way to send the sticker. If you did manage to figure this out, kindly share it with the rest of us. I've also placed a `help wanted` label on this issue.

**Comment by Secreto31126** [comment]
Stickers should be 512x512 .webp files, either for the static and the animated stickers.

https://upload.wikimedia.org/wikipedia/commons/f/fa/Logo_Icono.webp is a link I'm sure it should work (the API accepts it), although I didn't test it with your code.

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
