### ISSUE TITLE
ERR_UNHANDLED_REJECTION when trying to receive the Message from the bot

### ISSUE THREAD

**Issue by Mizar-Contasti** [tawn33y/whatsapp-cloud-api#46]
Hi Everyone, currently Im trying to receive  "Received your text message!" that the bot sends when receives a message.

Right now I'm receiving start message when I start the server. But when trying to send the message, I got this output.

![image](https://user-images.githubusercontent.com/60326716/203836599-9e75f019-5523-4f81-aecd-8ce4dc0c7ecb.png)

Right now My code is this ->

`
const { createBot } = require('whatsapp-cloud-api');

(async () => {
  try {
    // replace the values below
    const from = "";
    const token = "";
    const to = "";
    // const to = "524426581099";
    const webhookVerifyToken = "";

    // Create a bot that can send messages
    const bot = createBot(from, token);

    // Send text message
    const result = await bot.sendText(to, "Hello world");

    // Start express server to listen for incoming messages
    // NOTE: See below under `Documentation/Tutorial` to learn how
    // you can verify the webhook URL and make the server publicly available
    await bot.startExpressServer({
      webhookVerifyToken,
    });

    // Listen to ALL incoming messages
    // NOTE: remember to always run: await bot.startExpressServer() first
    bot.on("message", async (msg) => {
      console.log(msg);

      if (msg.type === "text") {
        await bot.sendText(msg.from, "Received your text message!");
      } else if (msg.type === "image") {
        await bot.sendText(msg.from, "Received your image!");
      }
    });
  } catch (err) {
    console.log(err);
  }
})();
`

**Comment by tawn33y** [comment]
To view the full error, try wrapping the `sendText` in a `try catch`, i.e:

```js
bot.on("message", async (msg) => {
  console.log(msg);

  try {
    if (msg.type === "text") {
      await bot.sendText(msg.from, "Received your text message!");
    } else if (msg.type === "image") {
      await bot.sendText(msg.from, "Received your image!");
    }
  } catch (err) {
    console.log(err);
  }
});
```

**Comment by tawn33y** [comment]
@Mizar-Contasti, can I mark this as completed?
