### ISSUE TITLE
Template buttons are not being handled

### ISSUE THREAD

**Issue by macols77** [tawn33y/whatsapp-cloud-api#52]
While it is now possible to handle responses to simple message buttons that we send directly to the user, the same is not possible if we send buttons as part of a WhatsApp template.
This is because templates with buttons have a different JSON structure and different types than a conventional message.

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
