### ISSUE TITLE
Getting error on sending template

### ISSUE THREAD

**Issue by karancuriositygym** [tawn33y/whatsapp-cloud-api#57]
Hi 

I have created a template and it is active.

I am sending template as below :
bot.sendTemplate(
        mobileNumber,
        "cg_quest_text",
       "en_US",
    [
        {
            "type": "body",
            "parameters": [{
                "type": "text",
                "text": "a) Career Counselling"
            }]
        }
       ])

I get error as below from meta :
   message: '(#132001) Template name does not exist in the translation',
    type: 'OAuthException',
    code: 132001,
    error_data: {
      messaging_product: 'whatsapp',
      details: 'template name (cg_quest_text) does not exist in en_US'
    },
    fbtrace_id: 'A5Ld_C-mecwFT9GzebFGU0m'
  }

Please guide as to what could be the issue.

**Comment by tommygarces** [comment]
If you have many phone numbers in WhatsApp Cloud API, verify if the template that you created is assigned to the actual phone number you are using. Sometimes it is created under the test number and not the one we use in production.

Another option to try would be to change the language template to English only, "en", and try it like that to see if it works.

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
