### ISSUE TITLE
message reaction feature

### ISSUE THREAD

**Issue by RyzorBent** [tawn33y/whatsapp-cloud-api#59]
Adding the ability to react to messages, [reaction](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#reaction-object)

**Comment by RyzorBent** [comment]
When running `npm run test` i get this error `    thrown: Object {
      "error": Object {
        "code": 12,
        "fbtrace_id": "AV_5w10PTT3UD9cyHjr3Udj",
        "message": "(#12) singular published story API is deprecated for versions v2.4 and higher",
        "type": "OAuthException",
      },
    }` where do i need to point to the latest supported API?

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
