### ISSUE TITLE
validate payloads as recommended by meta

### ISSUE THREAD

**Issue by hamza-shezad** [tawn33y/whatsapp-cloud-api#60]
as mentioned in https://developers.facebook.com/docs/graph-api/webhooks/getting-started, event notifications should be validated with the sha256 hash provided in the `X-Hub-Signature-256`
this will ensure secure communication, and help rejecting bad requests

**Comment by hamza-shezad** [comment]
i have a solution for this:

```ts
function validateHash(req, res, next) {
  if (req.method == "GET") {
    next();
    return;
  }

  const hash = createHmac("sha256", APP_SECRET).update(JSON.stringify(req.body)).digest("hex");
  const splitHash = req.get("X-Hub-Signature-256").split("=")[1];
  if (splitHash != hash) {
    res.sendStatus(200);
    return;
  }

  next();
}

whatsappApi.startExpressServer({
  useMiddleware: (app) => {
    app.use(WEBHOOK_PATH, validateHash)
  }
})
```

but there is a problem with this: if there is an `@` in the response, an invalid signature is produced. e.g. if i send a message with an email, the signatures do not match. this _may_ be due to `express.json` middleware in https://github.com/tawn33y/whatsapp-cloud-api/blob/main/src/startExpressServer.ts#L26 ?

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
