### ISSUE TITLE
Download Media

### ISSUE THREAD

**Issue by jessequartey** [tawn33y/whatsapp-cloud-api#62]
I think this is a good project, But the fact that it doesn't have a direct function to handle media download, or get you media URL is weird .  Try and add it or if there is one already then make it clear.

**Comment by RyzorBent** [comment]
I think the developer has abandoned the project by the looks of things.

**Comment by tawn33y** [comment]
Closing - please [read more here](https://github.com/tawn33y/whatsapp-cloud-api/issues/65).
